### ISSUE TITLE
How to set environment of this program and where can I download the DBpedia release 3.9

### ISSUE THREAD

**Issue by zhq2009** [HeikoPaulheim/sd-type-validate#1]
Hello,

I am very interested in this program. I keeping getting errors about running this program. I am wondering if you could tell me how I can set environment for this program ? eg. which IDE should I use and which packages I need to install etc. Are there associations between these .java files?

 I am interested in the DBpedia release 3.9, could you send me the link about where can I download the dataset? ( For example, where can I find the file "20151002-instance-types-transitive.ttl" )   

Thank you very much

**Comment by HeikoPaulheim** [comment]
Hi,

I've tested this with Eclipse, but the IDE should not be crucial.

The download for DBpedia 3.9 is here:
http://wiki.dbpedia.org/services-resources/datasets/data-set-39

You may also use a newer release and simply rename the files (or the references to the files in the code).

Best,
Heiko

**Comment by zhq2009** [comment]
Hello,

Thank you for your help. When I run the program I got the following errors:

Property assertions: load started
Exception in thread "main" org.apache.commons.compress.compressors.CompressorException: No Compressor found for the stream signature.
	at org.apache.commons.compress.compressors.CompressorStreamFactory.detect(CompressorStreamFactory.java:482)
	at org.apache.commons.compress.compressors.CompressorStreamFactory.createCompressorInputStream(CompressorStreamFactory.java:499)
	at user.LoadFiles.getBufferedReaderForCompressedFile(LoadFiles.java:316)
	at user.LoadFiles.loadProperties(LoadFiles.java:49)
	at user.Runner.main(Runner.java:27)

I did install these packages:

commons-compress-1.14-src；
brotli-master;
jwnl14-rc2;
xz-java-1.6;
h2-1.4.195.jar;

But the org.brotli.dec has errors in that package

I am wondering if you have any ideas about how to solve these problems.

Thank you very much.
